name: build-docker-image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build_and_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build And Push Docker Image
      run: |
        tag=$(date +%s)
        docker build . --file Dockerfile --tag blog:$tag
        docker login ccr.ccs.tencentyun.com --username=${{ secrets.TCR_USERNAME }} --password=${{ secrets.TCR_PASSWORD }}
        docker tag blog:$tag ccr.ccs.tencentyun.com/ezirmusitua/blog:$tag
        docker push ccr.ccs.tencentyun.com/ezirmusitua/blog:$tag
